# Generated by Django 6.0.7 on 2026-08-13 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID сессии (для неавторизованных)'),
        ),
    ]
