# Generated by Django 6.0.7 on 2026-08-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AddField(
            model_name='dish',
            name='slug',
            field=models.SlugField(blank=True, max_length=160, null=True, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(null=True, upload_to='dishes/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(null=True, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='weight',
            field=models.CharField(max_length=50, null=True, verbose_name='Вес'),
        ),
    ]
