# Generated by Django 6.0.7 on 2026-08-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_category_slug_dish_slug_alter_dish_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='spicy',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='vegetarian',
        ),
        migrations.AddField(
            model_name='dish',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='dish',
            name='deserts',
            field=models.BooleanField(default=False, verbose_name='Десерты'),
        ),
        migrations.AddField(
            model_name='dish',
            name='drinks',
            field=models.BooleanField(default=False, verbose_name='Напитки'),
        ),
        migrations.AddField(
            model_name='dish',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Основные блюда'),
        ),
        migrations.AddField(
            model_name='dish',
            name='salats',
            field=models.BooleanField(default=False, verbose_name='Салаты'),
        ),
        migrations.AddField(
            model_name='dish',
            name='soup',
            field=models.BooleanField(default=False, verbose_name='Супы'),
        ),
    ]
