# Generated by Django 6.0.7 on 2026-07-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('pickup', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('cook', 'Готовится'), ('ready', 'Готов'), ('done', 'Выдан'), ('cancel', 'Отменен')], default='new', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('dishes', models.ManyToManyField(to='menu.dish')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
